# Generated by Django 5.1.3 on 2024-11-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0003_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='Image',
            field=models.ImageField(blank=True, upload_to='offer/'),
        ),
    ]
